service: serverless-flask-sample
configValidationMode: error
plugins:
  - serverless-python-requirements
  - serverless-wsgi

provider:
  name: aws
  runtime: python3.10
  stage: dev
  region: us-east-1

custom:
  wsgi:
    app: src/app.app
    packRequirements: false



functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: 'GET /'
